### PR TITLE
Fix Failed with Invalid Microsoft Licensing Config

### LINKED ISSUE #187: Terraform apply failed with error Invalid Microsoft Licensing Config
### Describe the bug

Error: Failed to create SDDC: [Invalid Microsoft Licensing config provided for provisioning request MicrosoftLicensingConfig(windowsLicensing=DISABLED, mssqlLicensing=DISABLED, academicLicense=null). Please use Microsoft licensing publish APIs for activation. (code)115 ]

### Reproduction steps

provider "vmc" {
  refresh_token = var.api_token
  org_id = var.org_id
}

data "vmc_connected_accounts" "my_accounts" {
  account_number = var.aws_account_number
}

data "vmc_customer_subnets" "my_subnets" {
  connected_account_id = data.vmc_connected_accounts.my_accounts.id
  region               = var.sddc_region
}

resource "vmc_sddc" "sddc_1" {
  sddc_name           = var.sddc_name
  vpc_cidr            = var.vpc_cidr
  num_host            = 1
  provider_type       = "AWS"
  region              = data.vmc_customer_subnets.my_subnets.region
  vxlan_subnet        = var.vxlan_subnet
  delay_account_link  = false
  skip_creating_vxlan = false
  sso_domain          = "vmc.local"
  deployment_type = "SingleAZ"
  sddc_type ="1NODE"
  account_link_sddc_config {
    customer_subnet_ids  = [data.vmc_customer_subnets.my_subnets.ids[0]]
    connected_account_id = data.vmc_connected_accounts.my_accounts.id
  }
  microsoft_licensing_config {
   mssql_licensing = "ENABLED"
   windows_licensing = "DISABLED"
  }
}

1. Terraform plan
2. Terraform apply

### Expected behavior

SDDC is deployed successfully

### Additional context

When the below microsoft licensing config is not provided in SDDC resource, the deployment works.

resource "vmc_sddc" "sddc_1" {
  sddc_name           = var.sddc_name
  vpc_cidr            = var.vpc_cidr
  num_host            = 1
  provider_type       = "AWS"
  region              = data.vmc_customer_subnets.my_subnets.region
  vxlan_subnet        = var.vxlan_subnet
  delay_account_link  = false
  skip_creating_vxlan = false
  sso_domain          = "vmc.local"
  deployment_type = "SingleAZ"
  sddc_type ="1NODE"
  account_link_sddc_config {
    customer_subnet_ids  = [data.vmc_customer_subnets.my_subnets.ids[0]]
    connected_account_id = data.vmc_connected_accounts.my_accounts.id
  }

}

### PR DESCRIPTION
**Pull request by vasilsatanasov**
Fixes #187

Recent change in the backend API made impossible to process microsoft_licensing_config field during sddc deployment.

Moved microsoft_licensing_config setup on post sddc deployment Added microsoft_licensing_config.academic_license field handling

Testing done:
=== RUN   TestAccResourceVmcSddcZerocloud
=== PAUSE TestAccResourceVmcSddcZerocloud
=== CONT  TestAccResourceVmcSddcZerocloud
SDDC terraform_sddc_test_49pbjhxpev created successfully with id a79df99d-9cbc-4da6-b979-a75db3245aad
--- PASS: TestAccResourceVmcSddcZerocloud (120.44s)
PASS
5 times with and without microsoft_licensing_config setting

### CODE REVIEW

File: vmc/resource_vmc_sddc.go [hunk 1]
```diff
@@ -386,10 +393,18 @@ func resourceSddcCreate(d *schema.ResourceData, m interface{}) error {
 			return taskErr
 		}
 		err = resourceSddcRead(d, m)
-		if err == nil {
-			return nil
+		if err != nil {
+			return resource.NonRetryableError(err)
 		}
-		return resource.NonRetryableError(err)
+
```
Comment (dimitarproynov) [inline vmc/resource_vmc_sddc.go:399]: You can add a comment on why we're doing this post-create

**Review by dimitarproynov — APPROVED** [review]
LGTM!
