### PR TITLE
Fix Failed to read Customer Subnets

### LINKED ISSUE #191: Failed to read Customer Subnets : ["Invalid sddc type  specified."; (code)115 ]
### Describe the bug

The new provider version 1.13.1  is throwing a error when running Terraform plan.
Error :  Failed to read Customer Subnets : ["Invalid sddc type  specified."; (code)115 ]

### Reproduction steps

terraform {
  required_providers {
    vmc = {
      source  = "vmware/vmc"
      version = "1.13.1"
    }
  }
}

provider "vmc" {
  refresh_token = var.api_token
  org_id = var.org_id
}

data "vmc_connected_accounts" "my_accounts" {
  account_number = var.aws_account_number
}

data "vmc_customer_subnets" "my_subnets" {
  connected_account_id = data.vmc_connected_accounts.my_accounts.id
  region               = var.sddc_region
}

resource "vmc_sddc" "sddc_1" {
  sddc_name           = var.sddc_name
  vpc_cidr            = var.vpc_cidr
  num_host            = var.sddc_num_hosts
  provider_type       = "AWS" 
  region              = data.vmc_customer_subnets.my_subnets.region
  vxlan_subnet        = var.vxlan_subnet
  delay_account_link  = false
  skip_creating_vxlan = false
  sso_domain          = "vmc.local"
  deployment_type = "SingleAZ" 

  account_link_sddc_config {
    customer_subnet_ids  = [data.vmc_customer_subnets.my_subnets.ids[0]]
    connected_account_id = data.vmc_connected_accounts.my_accounts.id
  }
  microsoft_licensing_config {
   mssql_licensing = "ENABLED"
   windows_licensing = "DISABLED"
  }
  edrs_policy_type = "cost"
  enable_edrs = true
  min_hosts = 3
  max_hosts = 8
}

Run terraform plan

### Expected behavior

Terraform plan should be successful

### Additional context

The error is not seen when vmc provider version is set to 1.13.0

### PR DESCRIPTION
**Pull request by vasilsatanasov**
Fixes #191

The VMC provider was failing to retrieve Customer Subnets if SDDC type and instance type fields which are optional were not provided

Error:
Failed to read Customer Subnets : ["Invalid sddc type specified."; (code)115 ]

Fixed the wrong behavior of the provider, added a e2e test to verify that data for Customer Subnets can be retrieved with the required fields only.

Testing Done:
Successful terraform plan with the hcl provided in the issue and version of the provider with the fix
Successful run of acc tests locally

make testacc TESTARGS="-run='TestAccResourceVmcSddcZerocloud|TestAccResourceVmcClusterZerocloud|TestAccResourceVmcSiteRecoveryZerocloud|TestAccResourceVmcSrmNodeZerocloud|TestAccDataSourceVmcCustomerSubnetsBasic|TestAccDataSourceVmcConnectedAccountsBasic|TestAccDataSourceVmcOrgBasic|TestAccDataSourceVmcSddcBasic|TestAccResourceSddcGroupZerocloud' -parallel 4" TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run='TestAccResourceVmcSddcZerocloud|TestAccResourceVmcClusterZerocloud|TestAccResourceVmcSiteRecoveryZerocloud|TestAccResourceVmcSrmNodeZerocloud|TestAccDataSourceVmcCustomerSubnetsBasic|TestAccDataSourceVmcConnectedAccountsBasic|TestAccDataSourceVmcOrgBasic|TestAccDataSourceVmcSddcBasic|TestAccResourceSddcGroupZerocloud' -parallel 4 -timeout 240m
?       github.com/vmware/terraform-provider-vmc        [no test files]
?       github.com/vmware/terraform-provider-vmc/vmc/connector  [no test files]
?       github.com/vmware/terraform-provider-vmc/vmc/constants  [no test files]
=== RUN   TestAccDataSourceVmcConnectedAccountsBasic
--- PASS: TestAccDataSourceVmcConnectedAccountsBasic (4.79s)
=== RUN   TestAccDataSourceVmcCustomerSubnetsBasic
=== PAUSE TestAccDataSourceVmcCustomerSubnetsBasic
=== RUN   TestAccDataSourceVmcOrgBasic
--- PASS: TestAccDataSourceVmcOrgBasic (3.86s)
=== RUN   TestAccDataSourceVmcSddcBasic
--- PASS: TestAccDataSourceVmcSddcBasic (4.54s)
=== RUN   TestAccResourceVmcClusterZerocloud
=== PAUSE TestAccResourceVmcClusterZerocloud
=== RUN   TestAccResourceSddcGroupZerocloud
=== PAUSE TestAccResourceSddcGroupZerocloud
=== RUN   TestAccResourceVmcSddcZerocloud
=== PAUSE TestAccResourceVmcSddcZerocloud
=== RUN   TestAccResourceVmcSiteRecoveryZerocloud
=== PAUSE TestAccResourceVmcSiteRecoveryZerocloud
=== RUN   TestAccResourceVmcSrmNodeZerocloud
=== PAUSE TestAccResourceVmcSrmNodeZerocloud
=== CONT  TestAccDataSourceVmcCustomerSubnetsBasic
=== CONT  TestAccResourceVmcSddcZerocloud
=== CONT  TestAccResourceSddcGroupZerocloud
=== CONT  TestAccResourceVmcClusterZerocloud
--- PASS: TestAccDataSourceVmcCustomerSubnetsBasic (12.64s)
=== CONT  TestAccResourceVmcSrmNodeZerocloud
SDDC terraform_sddc_test_1uhyzid7h1 created successfully with id 8666d6d9-28ec-446b-8d14-f7237c83a8c0
--- PASS: TestAccResourceVmcSddcZerocloud (129.60s)
=== CONT  TestAccResourceVmcSiteRecoveryZerocloud
--- PASS: TestAccResourceSddcGroupZerocloud (177.85s)
Cluster for SDDC 00e87d17-1475-4c28-a34b-01d024845ae4 created successfully
--- PASS: TestAccResourceVmcSrmNodeZerocloud (279.83s)
--- PASS: TestAccResourceVmcSiteRecoveryZerocloud (218.82s)
--- PASS: TestAccResourceVmcClusterZerocloud (482.47s)
PASS
ok      github.com/vmware/terraform-provider-vmc/vmc    496.156s
testing: warning: no tests to run
PASS
ok      github.com/vmware/terraform-provider-vmc/vmc/sddcgroup  (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/vmware/terraform-provider-vmc/vmc/task       (cached) [no tests to run]

### CODE REVIEW

File: vmc/data_source_vmc_customer_subnets.go [hunk 1]
```diff
@@ -86,13 +86,24 @@ func dataSourceVmcCustomerSubnetsRead(d *schema.ResourceData, m interface{}) err
 	sddcID := d.Get("sddc_id").(string)
 	region := d.Get("region").(string)
 	numHosts := int64(d.Get("num_hosts").(int))
-	sddcType := d.Get("sddc_type").(string)
+
+	var sddcType *string
+	if len(d.Get("sddc_type").(string)) > 0 {
```
Comment (dimitarproynov) [inline vmc/data_source_vmc_customer_subnets.go:95]: You can add a comment on why we're doing this for future reference

**Review by dimitarproynov — APPROVED** [review]
LGTM!
