### PR TITLE
Fixes/iac 99

### LINKED ISSUE #30: Modifying sddc_type property in .tf file forces a redploy.
If SDDC is using the sddc_type property and it has been set to 1NODE, attempting to scale up this SDDC forces a redeploy. 
Screen Shot 2020-05-26 at 9 31 44 AM

### PR DESCRIPTION
**Pull request by eligah**
add the covert sddc in sddc resource update

### CODE REVIEW

**Comment by sumitAgrawal007** [comment]
Hi,
can you add bit more description as to what is the feature/change this PR is trying to achieve.

File: vmc/resource_vmc_sddc.go [hunk 1]
```diff
@@ -364,8 +367,47 @@ func resourceSddcUpdate(d *schema.ResourceData, m interface{}) error {
 	sddcID := d.Id()
 	orgID := (m.(*ConnectorWrapper)).OrgID
 
+	//Convert sddc from 1node to default
+	covertSddc := false
```
Comment (shylasrinivas) [inline vmc/resource_vmc_sddc.go]: space after // for all comments

File: vmc/resource_vmc_sddc.go [hunk 2]
```diff
@@ -364,8 +367,47 @@ func resourceSddcUpdate(d *schema.ResourceData, m interface{}) error {
...
+		oldType := oldTmp.(string)
+		newType := newTmp.(string)
+		//Validate for convert type params
+		if oldType == "1NODE" && (newType == "" || newType == "DEFAULT") {
+			log.Print("start to change the sddc type")
+			oldTmp, newTmp := d.GetChange("num_host")
+			oldNum := oldTmp.(int)
+			newNum := newTmp.(int)
+			if oldNum != 1 || newNum != 3 {
+				return fmt.Errorf("Convert sddc must from 1 host to 3 host")
```
Comment (shylasrinivas) [inline vmc/resource_vmc_sddc.go]: error message is not clear

Comment (saloneerege) [reply vmc/resource_vmc_sddc.go]: Can you reference sddc as SDDC ?

File: vmc/utils.go [hunk 3]
```diff
@@ -27,3 +27,13 @@ func ConvertStorageCapacitytoInt(s string) int64 {
 	storageCapacity := storageCapacityMap[s]
 	return storageCapacity
 }
+
```
Comment (saloneerege) [inline vmc/utils.go:30]: Can you add a description before this method as to why we are  doing this conversion ?

File: vmc/resource_vmc_sddc.go (hunk 1 above)
Comment (saloneerege) [inline vmc/resource_vmc_sddc.go]: Change variable name

Comment (eligah) [reply vmc/resource_vmc_sddc.go]: Okey

File: vmc/resource_vmc_sddc.go (hunk 2 above)
Comment (eligah) [reply vmc/resource_vmc_sddc.go]: Is "Scale SDDC must from 1 host to 3 hosts" okey?

**Comment by eligah** [comment]
This PR is mainly to add the feature for SDDC scale up from 1node type to default in resourceSddcUpdate.

**Comment by eligah** [comment]
> Hi,
> can you add bit more description as to what is the feature/change this PR is trying to achieve.

I have added it below.

**Review by eligah — COMMENTED** [review]
Add changes

File: vmc/resource_vmc_sddc.go [hunk 4]
```diff
@@ -364,8 +367,47 @@ func resourceSddcUpdate(d *schema.ResourceData, m interface{}) error {
...
+	// Convert sddc from 1node to default
+	toConvertSddc := false
+	if d.HasChange("sddc_type") {
+		oldTmp, newTmp := d.GetChange("sddc_type")
+		oldType := oldTmp.(string)
+		newType := newTmp.(string)
+
+		// Validate for convert type params
+		if oldType == "1NODE" && (newType == "" || newType == "DEFAULT") {
+			oldTmp, newTmp := d.GetChange("num_host")
```
Comment (saloneerege) [inline vmc/resource_vmc_sddc.go]: oldTmp should be d.Get("num_host").(int) right ?

File: vmc/resource_vmc_sddc.go [hunk 5]
```diff
@@ -364,8 +367,47 @@ func resourceSddcUpdate(d *schema.ResourceData, m interface{}) error {
...
+			oldNum := oldTmp.(int)
```
Comment (saloneerege) [inline vmc/resource_vmc_sddc.go]: you can directly get oldNum := d.GetChange("num_host").(int) Remove multiple variables oldNum, oldType, newNum, newType usage.

File: vmc/resource_vmc_sddc.go (hunk 1 above)
Comment (eligah) [reply vmc/resource_vmc_sddc.go]: It is outdated, I have changed in the lastest PR to toConvertSddc

File: vmc/resource_vmc_sddc.go (hunk 4 above)
Comment (eligah) [reply vmc/resource_vmc_sddc.go]: I will change it like your next comments. Since this format is the same as we used in sddcUpdate.

File: vmc/resource_vmc_sddc.go (hunk 5 above)
Comment (saloneerege) [reply vmc/resource_vmc_sddc.go]: Make these changes else where in the code if needed

File: vmc/resource_vmc_sddc.go [hunk 6]
```diff
@@ -364,8 +367,47 @@ func resourceSddcUpdate(d *schema.ResourceData, m interface{}) error {
...
+			newNum := newTmp.(int)
+			if oldNum != 1 || newNum != 3 {
+				return fmt.Errorf("Scale SDDC must from 1 host to 3 hosts")
```
Comment (saloneerege) [inline vmc/resource_vmc_sddc.go]: Change error message to something like "Scale up for SDDC must be from 1 host to 3 hosts"

File: vmc/resource_vmc_sddc.go [hunk 7]
```diff
@@ -364,8 +367,47 @@ func resourceSddcUpdate(d *schema.ResourceData, m interface{}) error {
...
+			}
+			convertClient := sddcs.NewDefaultConvertClient(connector)
+			task, err := convertClient.Create(orgID, sddcID)
+
+			if err != nil {
+				return HandleUpdateError("SDDC", err)
+			}
+			tasksClient := orgs.NewDefaultTasksClient(connector)
+			err = resource.Retry(d.Timeout(schema.TimeoutUpdate), func() *resource.RetryError {
+				task, err := tasksClient.Get(orgID, task.Id)
```
Comment (saloneerege) [inline vmc/resource_vmc_sddc.go]: You need to add a call to authenticate() since the token expires after 30 mins

File: vmc/resource_vmc_sddc.go [hunk 8]
```diff
@@ -334,7 +333,6 @@ func resourceSddcRead(d *schema.ResourceData, m interface{}) error {
 	d.Set("provider", sddc.Provider)
 	d.Set("account_link_state", sddc.AccountLinkState)
 	d.Set("sddc_access_state", sddc.SddcAccessState)
-	d.Set("sddc_type", sddc.SddcType)
```
Comment (eligah) [inline vmc/resource_vmc_sddc.go:335]: This line is duplicate with line 332

File: go.sum [hunk 9]
```diff
@@ -550,4 +550,4 @@ honnef.co/go/tools v0.0.0-20190418001031-e561f6794a2a/go.mod h1:rf3lG4BRIbNafJWh
 honnef.co/go/tools v0.0.0-20190523083050-ea95bdfd59fc/go.mod h1:rf3lG4BRIbNafJWhAfAdb/ePZxsR/4RtNHQocxwk9r4=
 howett.net/plist v0.0.0-20181124034731-591f970eefbb/go.mod h1:vMygbs4qMhSZSc4lCUl2OEE+rDiIIJAIdR4m7MiMcm0=
 rsc.io/binaryregexp v0.2.0/go.mod h1:qTv7/COck+e2FymRvadv62gMdZztPaShugOCi3I+8D8=
-rsc.io/pdf v0.1.1/go.mod h1:n8OzWcQ6Sp37PL01nO98y4iUCRdTGarVfzxY20ICaU4=
```
Comment (eligah) [inline go.sum:553]: I have not idea why diff happen between lines

File: vmc/resource_vmc_sddc.go (hunk 5 above)
Comment (eligah) [reply vmc/resource_vmc_sddc.go]: There is not an elegant way to convert multiple return values without temp variables

File: vmc/resource_vmc_sddc.go [hunk 10]
```diff
@@ -429,9 +488,9 @@ func resourceSddcUpdate(d *schema.ResourceData, m interface{}) error {
 			return err
 		}
 	}
+
 	// Update sddc name
 	if d.HasChange("sddc_name") {
-		sddcClient := orgs.NewDefaultSddcsClient(connector)
```
Comment (eligah) [inline vmc/resource_vmc_sddc.go:432]: Move to the beginning part of the function

**Review by eligah — COMMENTED** [review]
Add comments for this PR

**Review by sumitAgrawal007 — COMMENTED** [review]
LGTM

File: vmc/resource_vmc_sddc.go [hunk 11]
```diff
@@ -385,9 +387,66 @@ func resourceSddcDelete(d *schema.ResourceData, m interface{}) error {
...
+		newType := newTmp.(string)
+
+		// Validate for convert type params
+		if oldType == "1NODE" && (newType == "" || newType == "DEFAULT") {
+			oldTmp, newTmp := d.GetChange("num_host")
+			oldNum := oldTmp.(int)
+			newNum := newTmp.(int)
+
+			if oldNum != 1 {
+				return fmt.Errorf("Scale SDDC must from 1 host type")
```
Comment (shylasrinivas) [inline vmc/resource_vmc_sddc.go]: I am a little confused by this error message

File: vmc/resource_vmc_sddc.go [hunk 12]
```diff
@@ -385,9 +387,66 @@ func resourceSddcDelete(d *schema.ResourceData, m interface{}) error {
...
+					if *task.Status != "FINISHED" {
+						return resource.RetryableError(fmt.Errorf("expected hosts to be updated but were in state %s", *task.Status))
+					}
+					return resource.NonRetryableError(resourceSddcRead(d, m))
+				})
+				if err != nil {
+					return err
+				}
+			} else {
+				return fmt.Errorf("Convert sddc error from %d to %d is not supported", oldNum, newNum)
```
Comment (shylasrinivas) [inline vmc/resource_vmc_sddc.go]: can this error be re-phrased?

**Review by shylasrinivas — CHANGES_REQUESTED** [review]
rephrase error messages

File: vmc/resource_vmc_sddc.go [hunk 13]
```diff
@@ -385,9 +387,66 @@ func resourceSddcDelete(d *schema.ResourceData, m interface{}) error {
...
+			newNum := newTmp.(int)
+
+			if oldNum != 1 {
+				return fmt.Errorf("Scale SDDC must from 1 host type")
+			} else if newNum == 2 { // 2node sddc creation
+				err := resourceSddcDelete(d, m)
+				if err != nil {
+					return err
+				}
+				return resourceSddcCreate(d, m)
```
Comment (saloneerege) [inline vmc/resource_vmc_sddc.go:408]: Have you tested if this part works ?

File: vmc/utils.go [hunk 14]
```diff
@@ -27,3 +27,16 @@ func ConvertStorageCapacitytoInt(s string) int64 {
...
+// Do a mapping for deployment_type field
+// When refresh/import state, return value of vmc api should be converted to uppercamel case in terraform
```
Comment (saloneerege) [inline vmc/utils.go]: Fix typo - VMC API

File: vmc/resource_vmc_sddc.go (hunk 11 above)
Comment (saloneerege) [reply vmc/resource_vmc_sddc.go]: @eligah Please reword error message

File: vmc/resource_vmc_sddc.go (hunk 12 above)
Comment (saloneerege) [reply vmc/resource_vmc_sddc.go]: @eligah Please fix error message

File: vmc/resource_vmc_sddc.go [hunk 15]
```diff
@@ -385,9 +387,66 @@ func resourceSddcDelete(d *schema.ResourceData, m interface{}) error {
 func resourceSddcUpdate(d *schema.ResourceData, m interface{}) error {
 	connector := (m.(*ConnectorWrapper)).Connector
 	esxsClient := sddcs.NewDefaultEsxsClient(connector)
+	sddcClient := orgs.NewDefaultSddcsClient(connector)
 	sddcID := d.Id()
 	orgID := (m.(*ConnectorWrapper)).OrgID
 
+	// Convert sddc from 1node to default
```
Comment (saloneerege) [inline vmc/resource_vmc_sddc.go]: Please rephrase commented line to " Convert SDDC from 1NODE to DEFAULT"

**Review by saloneerege — CHANGES_REQUESTED** [review]

File: vmc/resource_vmc_sddc.go (hunk 13 above)
Comment (eligah) [reply vmc/resource_vmc_sddc.go:408]: Yes, it will create a new sddc after the older one has been deleted

File: vmc/resource_vmc_sddc.go (hunk 11 above)
Comment (eligah) [reply vmc/resource_vmc_sddc.go]: I found the piece of code will not happen. I just deleted this if branch

**Review by eligah — COMMENTED** [review]
Rephrase the comments

**Review by saloneerege — APPROVED** [review]

File: vmc/resource_vmc_sddc.go [hunk 16]
```diff
@@ -383,9 +385,63 @@ func resourceSddcDelete(d *schema.ResourceData, m interface{}) error {
...
+					if *task.Status != "FINISHED" {
+						return resource.RetryableError(fmt.Errorf("expected hosts to be updated but were in state %s", *task.Status))
+					}
+					return resource.NonRetryableError(resourceSddcRead(d, m))
+				})
+				if err != nil {
+					return err
+				}
+			} else {
+				return fmt.Errorf("scaling SDDC is not supported. please check sddc_type and num_host")
```
Comment (shylasrinivas) [inline vmc/resource_vmc_sddc.go]: p -> P

File: vmc/resource_vmc_sddc.go [hunk 17]
```diff
@@ -383,9 +385,63 @@ func resourceSddcDelete(d *schema.ResourceData, m interface{}) error {
...
+					task, err := tasksClient.Get(orgID, task.Id)
+
+					if err != nil {
+						if err.Error() == (errors.Unauthenticated{}.Error()) {
+							log.Print("Auth error", err.Error(), errors.Unauthenticated{}.Error())
+							err = m.(*ConnectorWrapper).authenticate()
+							if err != nil {
+								return resource.NonRetryableError(fmt.Errorf("authentication error from Cloud Service Provider : %s", err))
+							}
+							return resource.RetryableError(fmt.Errorf("instance scaling still in progress"))
```
Comment (shylasrinivas) [inline vmc/resource_vmc_sddc.go]: should instance be rephrased to sddc?

File: vmc/utils.go [hunk 18]
```diff
@@ -27,3 +27,16 @@ func ConvertStorageCapacitytoInt(s string) int64 {
 	storageCapacity := storageCapacityMap[s]
 	return storageCapacity
 }
+
+// Do a mapping for deployment_type field
+// When refresh/import state, return value of VMC API should be converted to uppercamel case in terraform
```
Comment (shylasrinivas) [inline vmc/utils.go]: When -> During

File: vmc/utils.go [hunk 19]
```diff
@@ -27,3 +27,16 @@ func ConvertStorageCapacitytoInt(s string) int64 {
 	storageCapacity := storageCapacityMap[s]
 	return storageCapacity
 }
+
+// Do a mapping for deployment_type field
```
Comment (shylasrinivas) [inline vmc/utils.go]: remove Do a -> // Mapping for deployment_type field

File: vmc/utils.go [hunk 20]
```diff
@@ -27,3 +27,16 @@ func ConvertStorageCapacitytoInt(s string) int64 {
...
+// When refresh/import state, return value of VMC API should be converted to uppercamel case in terraform
+// to keep consistency
```
Comment (shylasrinivas) [inline vmc/utils.go]: keep -> maintain

**Review by shylasrinivas — CHANGES_REQUESTED** [review]
minor typos

**Review by shylasrinivas — APPROVED** [review]

**Comment by eligah** [comment]
Fixed the issue #30

**Review by eligah — COMMENTED** [review]
fixed #30
